import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/common/Footer";
import OfflineProvider from "@/components/offline/OfflineProvider";
import { SyncStatusProvider } from "@/lib/offline/SyncStatusContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SalesPro - Dashboard",
  description: "Generated by Sirius Tech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <OfflineProvider>
          <SyncStatusProvider>
            <main className="min-h-screen">{children}</main>
          </SyncStatusProvider>
        </OfflineProvider>
        <Footer />
      </body>
    </html>
  );
}
