import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Blinker } from "next/font/google";


// import React from 'react';
// import Link from 'next/link';
// import logo from '../assets/images/logo.png';
// import Image from 'next/image';
// import { useState } from 'react';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const inter = Inter({ subsets: ["latin"] });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SalesPro - Dashboard",
  description: "Generated by Sirius Tech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        {/* Header Section Starts Here */}
        {/* <Header /> */}
        {/* Right Sidebar(Connect Wallet) Starts Here */}

        {/* <Sidebar /> */}
        {/* Main Section Starts Here */}
        {children}
        {/* Footer Section Starts Here */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
